### ISSUE TITLE
Stop using Local resolvers 

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#100]
If we're using it? They're deprecated https://www.apollographql.com/docs/react/local-state/local-resolvers/

It looks pretty similar to Local-only fields which is the suggested alternative https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/

**Comment by Powersource** [comment]
Looks like we might not be using them?

https://github.com/Edgeryders-Participio/realities/blob/master/ui/src/services/apolloClient/localState.js#L4

**Comment by aerugo** [comment]
Looks like we can close this?
