### ISSUE TITLE
Merge the borderland branch into master

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#101]

**Comment by Powersource** [comment]
Anything in there that we'd want to avoid? The branch seems strictly ahead of master atm, so it's hopefully easy to merge

**Comment by Powersource** [comment]
Made a PR for it. Let's wait with merging that until i've merged the Make it work branch first though

https://github.com/Edgeryders-Participio/realities/pull/102

**Comment by aerugo** [comment]
Agreed. Lets also do something more sane than this hack for templates:
https://github.com/Edgeryders-Participio/realities/commit/d81752b0e6be688677e57a6a7d51334614cb9ff2
