### ISSUE TITLE
Fix ListGroup tag on search

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#103]
Basically this thread https://github.com/Edgeryders-Participio/realities/pull/94#pullrequestreview-485145243

Also applies to this file `ui/src/components/TypeaheadInput/components/TypeaheadResultsContainer/components/TypeaheadResults/TypeaheadResults.js` (sidenote: why are we essentially implementing this twice? do the components differ in any meaningful way?)

**Comment by gustavlrsn** [comment]
Maybe `React.forwardRef` could be used? Something like this:

```
const ListGroupWithRef = React.forwardRef((props, ref) => {
  return (
    <ListGroup {...props} innerRef={ref}>
      {props.children}
    </ListGroup>
  )
}
```
and then use it like this:
```
...
<ListGroupWithRef flush {...getMenuProps()} />
    ...
```

**Comment by Powersource** [comment]
I'm not 100 on refs yet but does it work to set `innerRef`? Reading here it doesn't sound like a general thing https://stackoverflow.com/questions/53211627/what-is-innerref-in-reactjs and it doesn't seem to be a part of ListGroup's implementation either https://github.com/reactstrap/reactstrap/blob/master/src/ListGroup.js

**Comment by aerugo** [comment]
Not sure I understand this issue. What does this relate to?

**Comment by Powersource** [comment]
A small accessibility detail. I think this will get fixed/disappear once we switch away from reactstrap.
