### ISSUE TITLE
Only allow deleting needs if they don't have any resps

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#116]
* [x] Disallow in the api
* [x] Disallow in the frontend
* [x] Add the cypher function below to a db migration to make sure we don't have any undeleted resps lying around

------
old issue:

Reproduction in production:

1. Go to https://realities.blivande.com
2. Search for "Cooking" or "Toilets"
3. Select the search result
4. Blank page and errors in the console

**Comment by Powersource** [comment]
My current guess is this, I still need to try reproducing:

1. Create a need "Food" and a resp for it, "Cooking"
2. Delete Food. I think the app used to tell you you had to delete all the underlying resps as well but you can get past that somehow now.
3. Be able to still find Cooking through either search, or the Graph, if you click the resp in either though it crashes. You can find it in the profile graphs too but clicking it there doesn't crash it.

**Comment by Powersource** [comment]
Related branch I think https://github.com/Edgeryders-Participio/realities/tree/delete-resp-before-deleting-need

**Comment by aerugo** [comment]
This is still an issue, see https://realities.platoproject.org/ and search for "Budget". One of those is a ghost-node that crashes front-end. Bumping this to high priority as this has now caused quite a few UX issues when people try to create budget dependencies to the wrong node.

**Comment by aerugo** [comment]
Another example of this behavior here: https://realities.platoproject.org/blivande/profile/0b212b35-3eb3-4bbc-b0e7-b36672318bb7

For some reason, there are a bunch of Nodes available to the Blivande instance that do not belong to the Blivande org. None of the nodes below should be on the Blivande org.

<img width="705" alt="Screenshot 2021-01-08 at 00 38 26" src="https://user-images.githubusercontent.com/7785081/103956925-d8ff3b00-5149-11eb-84ee-91f5c65b2966.png">

**Comment by Powersource** [comment]
Looking directly in neo4j the nodes look like they belong(ed) to blivande. The pink 5f21 node is the blivande node. They all belong to Needs that have been deleted though.

![image](https://user-images.githubusercontent.com/1427063/104012448-1b5b6300-51b0-11eb-87a9-63891ce071c9.png)

Ran this on prod now to clean it up

```
MATCH (n:Need)<-[:FULFILLS]-(r:Responsibility) WHERE EXISTS (n.deleted) AND NOT EXISTS (r.deleted) SET r.deleted=timestamp() return r
```
