### ISSUE TITLE
Fix "We're sorry, but something went wrong" when registering an account

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#126]
Originally found here, https://github.com/Edgeryders-Participio/realities/pull/121#issuecomment-712228257 , but also reproduced by I think both Hugi and Gustav. Still creates the account and you can log in, but users shouldn't be greeted by this.

![image](https://user-images.githubusercontent.com/1427063/97323407-0d649a00-1871-11eb-86a6-f474e7f0cc65.png)

**Comment by Powersource** [comment]
https://github.com/keycloak/keycloak-containers/blob/master/server/README.md#specify-log-level Tried changing the log level to ALL, and then viewing the logs with dokku (important to increase the nr of lines [with -n](https://github.com/dokku/dokku/blob/master/docs/deployment/logs.md#behavioral-modifiers)) and there was a lot of logs but nothing that really looked like an error/anything very relevant to it breaking, although I didn't read it super carefully.

**Comment by Powersource** [comment]
This didn't happen when I made my second account. I think if another person can verify that it seems to be fixed then I'll close this

**Comment by aerugo** [comment]
Yup, seems to have been resolved.
