### ISSUE TITLE
Redefining the realizer feature

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/realities#127]
We want to move Realities away from individual realizers to a more group-based approach. 
In addition, we also want to simplify the system by only applying realizers to Responsibilities and not to Needs. Needs should only have guides.

* Allow assigning multiple realizers to a responsibility https://github.com/Edgeryders-Participio/realities/issues/212
* Remove the realizer field from needs https://github.com/Edgeryders-Participio/realities/issues/211
* Guides remain unchanged - only one guide per need or responsibility

**Comment by Powersource** [comment]
Split this into separate issues, see links in original post
