### ISSUE TITLE
Auth seems to have problems refreshing tokens

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#151]
I've noticed it the most when coming back after having suspended my computer and trying to e.g. add a resp, after I get "Error: User isn't authenticated" in the console and the page crashes. At this point my email is still showing in the top right corner. It might also happen after I've simply been logged in for a while, i.e. not just after having suspended my computer.

**Comment by aerugo** [comment]
This also happened with Auth0 so it might be somewhere in the client.

**Comment by Powersource** [comment]
Do you remember if with auth0 you still looked logged in even after refreshing the page? I think the reactivity might have been lacking in some parts, but I'm guessing it might have rendered you properly as logged out if you refreshed. Because a problem now is that it still seems to think you're logged in even after page refreshes :confused:

**Comment by Powersource** [comment]
And yuup it happens for me without suspending (guessing after 15 min)

**Comment by Powersource** [comment]
Note to self about oidc-client docs that they're forgotten to merge https://github.com/IdentityModel/oidc-client-js/issues/339

**Comment by Powersource** [comment]
The examples I can find seem to have one route /auth-callback and one /silent-callback (linked from here https://github.com/IdentityModel/oidc-client-js/issues/1206 ) that call signinRedirectCallback and signinSilentCallback respectively. But there's apparently an undocumented https://github.com/IdentityModel/oidc-client-js/issues/1253 signinCallback that oidc-react uses https://github.com/bjerkio/oidc-react/pull/249 so our current code should work in that aspect.

**Comment by Powersource** [comment]
More debugging lead to this https://github.com/bjerkio/oidc-react/issues/361

**Comment by Powersource** [comment]
And I have a PR for it! https://github.com/bjerkio/oidc-react/pull/363

**Comment by Powersource** [comment]
That's merged and I've updated to the new oidc-react in #165 so this should be fixed in production very soon :)
