### ISSUE TITLE
Add Org node that has a HAS relationship to all nodes (within that org)

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#156]
Based on https://github.com/Edgeryders-Participio/realities/issues/117

I've previously called orgId tenantId in some issues/code

All node labels for reference
```
Person (doesn't need prop)
Need
Responsibility
Info
ResponsibilityTemplate
RealitiesDBVersion (doesn't need prop)
```

Why we want this:
* Filtering when displaying "everything" of something, e.g. in the Needs list, or in search. We only want to display stuff from the viewed org. For this I think we'd only need to add the prop to Needs, Responsibilities, and ResponsibilityTemplate.
* Access control. We don't want people editing/drawing edges to nodes from other orgs. So we might want some way to control this too for e.g. Info nodes. Could in theory check if the Info node is connected to e.g. a resp with the right orgId. We could in theory do this for all labels, and connect everything to an Org node, Hugi suggested this. But I'm gonna guess checking props is faster and simpler, so maybe let's just add the prop to Info as well.

Where we need to add it:
* Add a migration to add it to old nodes. Add the placeholder org's id
* In mutations that create nodes that should have orgIds (do this one first)

---

Edit: Ok we're doing stuff a bit differently now, see thread

**Comment by aerugo** [comment]
> We could in theory do this for all labels, and connect everything to an Org node, Hugi suggested this. But I'm gonna guess checking props is faster and simpler, so maybe let's just add the prop to Info as well.

I'm not so sure. I'm by no means certain, but my understanding is that navigating by relationships is faster. As I understand it, traversing to any node that is linked to another starting node is always O(1) while searching for a node based on a prop is a search operation. [Traversing the graph by its relations is pointer chasing.](https://neo4j.com/blog/computer-hardware-native-graph-databases/). If that is the case, the fastest way to get all Needs belonging to an org should be 
`MATCH (o:Organization)-[:NEEDS]->(n:Need)`, and the fastest way to get all Responsibilities would be `MATCH (o:Organization)-[:NEEDS]->(n:Need)<-[:FULFILLS]-(r: Responsibility)` ... etc.

**Comment by Powersource** [comment]
Hmm ok. Will research more.

One thing to consider is that "getting all needs/resps" is only something a couple of the graphql resolvers need to do. Most of the resolvers (e.g. we have a lot of mutations) only operate on one or a few nodes. However maybe it's the get-all queries that run the most often, so they shouldn't be too slow. But I'm also considering code complexity here, I worry that e.g. functions like `getRelationshipQuery` would look a lot more complex if we're doing `traversing` rather than `props`. Maybe we could have both at the same time? Maybe start with `props` to keep stuff simple and when we need to optimize stuff we can add the `Organization` nodes to be able to easily find its Needs and Resps? Also worth noting (I described it more in the Research issue) that indexing is possible on props, it's just maybe not entirely intended usage of neo4j.

`traversing` (having an `Organization` node that points to all its Needs, that then in turn points at other nodes in the org):
* getting all nodes of a type: almost O(1)?
* checking if a node with a specific `nodeId` is in the org: O(1) (higher constant)
* code complexity: low for get-all. prob often high on specific
`props` (having an `orgId` prop on all nodes):
* getting all: O(n) or something like that
* specific: O(1)
* code complexity: prob generally low

**Comment by erikfrisk** [comment]
I'm torn.

How about an Org node that "owns" nodes of all labels? If it's connected to all nodes, any query or mutation would just need an extra MATCH clause to make sure the node you're interested in is owned by the correct org. I don't think that would cause more code complexity than a property.

Only connecting it to needs would make for a more clean graph, but maybe connecting it to everything is worth it for simpler queries?

I agree with Hugi that an org node feels more neo4j-like than a property, but I'm no graph database expert so take it for what it's worth. 

Another solution to reduce code complexity could be to connect the org node only to needs, and to define reusable MATCH clauses for checking authorization for each label. Something like this: 

```
const orgAuth = {
  Need: (orgId) => `MATCH (o:Organization)-[:NEEDS]->(n:Need) WHERE o.id = ${orgId}`,
  Responsibility: (orgId) => 
    `MATCH (o:Organization)-[:NEEDS]->(:Need)<-[:FULFILLS]-(r: Responsibility) WHERE o.id = ${orgId}`,
  ...
};

export function findNodeByLabelAndId(driver, label, nodeId, orgId) {
  const query = `
    ${orgAuth[label](orgId)}
    MATCH (n:${label} {nodeId: $nodeId})
    WHERE NOT EXISTS(n.deleted)
    RETURN n
  `;
  return runQueryAndGetRecord(driver.session(), query, { nodeId });
}
```

**Comment by Powersource** [comment]
> How about an Org node that "owns" nodes of all labels?

That sounds like a beautiful compromise! Prob going with this one unless anyone has any objections :)

btw nice lecture on their internals https://www.youtube.com/watch?v=oALqiXDAYhc

**Comment by aerugo** [comment]
Agreed, this is the best solution!
