### ISSUE TITLE
Make sure letsencrypt is refreshed on the server

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#158]
Got an email the other day that started like this

> Hello,
>
> Your certificate (or certificates) for the names listed below will expire in 19 days (on 27 Dec 20 12:18 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

Would be annoying if it broke while I was taking a holiday break so let's look into this before then :P

**Comment by aerugo** [comment]
When running certbot, auto renew is just a matter of a line in the config.
Should be the same in this case, though I’m not sure exactly what our setup
config looks like.

**Comment by Powersource** [comment]
We're getting letsencrypt through a dokku plugin that's worked well so far. Hopefully also just a simple config option

**Comment by LiamK** [comment]
I'm pretty sure certbot tries to renew silently and doesn't start
sending those messages unless the automatic renewal is failing for some
reason.

**Comment by Powersource** [comment]
Got the same email for auth.platoproject.org now

**Comment by Powersource** [comment]
ok so apparently running e.g. `dokku letsencrypt realities` (i was just trying to get the helptext :p ) refreshes it. will try to look up how to make it actually automatic

**Comment by Powersource** [comment]
Tried doing `dokku letsencrypt:cron-job --add` like the [readme says](https://github.com/dokku/dokku-letsencrypt) and then I got

```
no crontab for dokku
-----> Added cron job to dokku's crontab.
```

It claims that

```
# dokku letsencrypt:cron-job
       Job added. Use --remove to remove the cron job.
```

but it hasn't refreshed it for auth.platoproject.org yet. Now I did `dokku letsencrypt:auto-renew` so everything was refreshed including dreams. I guess we'll see in feb/march if the cronjob actually works.
