### ISSUE TITLE
Write and deploy tests

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/realities#16]
Yeah. Tests. As stated by @erikfrisk, "because we're not animals".

**Comment by Powersource** [comment]
This would be pretty neat (maybe not right now but not too far in the future). I'm thinking e2e tests because that's what I'm used to. Time consuming parts here would be to have to e.g. set up a new neo4j server and making fixtures for it.

**Comment by Powersource** [comment]
Note to self, prob pretty easy to just run neo4j (and prob mongo) in docker, by default we'd get a clean db and it'd delete itself after shutdown
