### ISSUE TITLE
Remove Loomio integration

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#187]
Right now there's the cronjob every hour that pulls discussions from e.g. the borderland loomio every hour but I think the only effect that has is that it puts them into nodes in neo4j. I don't think we ever use these nodes though? And we're planning close integration with Discourse instead.

thoughts @aerugo ?

---

* [x] Remove scraper
* [ ] ~~Add migration to remove old nodes added by it (be careful not to remove the resp description history nodes)~~ ok skipping that one, we use some of the info nodes for Related discussion links and those aren't getting cleaned up either, if we really want to we can clean all of the unused ones up later. maybe also just limited to my local installation, we didn't add the loomio env vars to prod
* [x] Uninstall unused deps

**Comment by aerugo** [comment]
Yeah, get rid of it.
