### ISSUE TITLE
Clarify how a user becomes visible to an org

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/realities#190]
Since we now have a single login to Plato, we need to clarify how a user becomes visible to an org on Realities.

**Comment by Powersource** [comment]
atm I think every user (with a node in neo4j) shows up in search in any org. and you get a node when you log into realities with your plato account (it's created in `ui/src/App/components/AuthRoutesContainer/components/AuthCallback/AuthCallback.js`)

**Comment by aerugo** [comment]
Yes, and that's probably too messy when we start getting a lot of orgs. 
I would opt for some sort of solution where person node becomes available to the org when a user has "joined" the org - similarly to how users need to join an event on Dreams to be available to add as collaborators.

**Comment by Powersource** [comment]
I think the simplest way to do that atm would be to get the list of users with OrgMember documents for this org in plato core. That document is created when a user visits a certain org (and in the future would be a more formal membership proof).

**Comment by aerugo** [comment]
Yeah, that makes sense. But how does Realities currently count a "visit"?

**Comment by Powersource** [comment]
It's this line that creates it https://github.com/Edgeryders-Participio/realities/blob/master/api/src/index.js#L52 and that line is run whenever `createContext` is run, and that is run every time the user makes a query/mutation, so as soon as the user gets e.g. the list of all current Needs.

**Comment by aerugo** [comment]
Ah, okay! Fair enough, that's good for now. :)
