### ISSUE TITLE
Fix crash when multiple tabs open and logging out in one of them

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#191]
Related links

https://github.com/IdentityModel/oidc-client-js/issues/49
https://github.com/IdentityModel/oidc-client-js/issues/168
https://github.com/IdentityModel/oidc-client-js/issues/830
https://github.com/Edgeryders-Participio/realities/issues/162

Doing this https://github.com/IdentityModel/oidc-client-js/issues/830#issuecomment-506297570 (note it's supposed to be signinSilent not signInSilent) right after setting up our userManager at first seemed to have fixed the issue, but then made me run into errors including crashing the page with "Unhandled Rejection (Error): invalid_grant" (thrown by oidc-client).

**Comment by aerugo** [comment]
Those errors happen when we log out manually, correct?

**Comment by Powersource** [comment]
Yep. Reproduction:
* Log in in one tab (tab 1).
* Open another tab (tab 2), you are automatically logged in there.
* Log out in tab 2 (although other way around works as well).
* Refresh tab 1, crash.

**Comment by Powersource** [comment]
Merged now

**Comment by Powersource** [comment]
Tried adding a .catch for the error and that stops the instant crashing but instead makes the user crash when they try to perform something that requires auth, which is probably worse.

**Comment by Powersource** [comment]
Some clues in this documentation issue but even they seem confused https://github.com/IdentityModel/oidc-client-js/issues/339

>  Just do a signinSilent before you even think about calling getUser. If it resolves, the User you get immediately after is valid; if it rejects you need to do an interactive login e.g. with signinRedirect.
>
> The querySessionStatus method on UserManager may be able to give complete status information, but it performs a callback to silent_redirect_uri that has a very different query than signinSilent, and somehow while I was doing that I didn't think to pass that to signinSilentCallback (probably because I hadn't figured out that the different URLs MUST be distinct and was trying to detect based on the query). But it seems silly to do a querySessionStatus which does almost the same thing as a signinSilent but might have to be followed by a signinSilent anyway.
>
> ... But I've also seen cases where signinSilent seems to generate a user with invalid tokens, so I think I'm still missing something here.

**Comment by Powersource** [comment]
TODO: try https://github.com/IdentityModel/oidc-client-js/issues/830#issuecomment-757029230

**Comment by Powersource** [comment]
Closing this through https://github.com/Edgeryders-Participio/realities/pull/196 now and putting my future faith in https://github.com/Edgeryders-Participio/realities/issues/195

**Comment by Powersource** [comment]
oh and fwiw I realized that the "crash" in the title here was only in dev, it was an uncaught promise and that I guess crashes the dev react renderer but not in prod. Either way it's getting caught now.
