### ISSUE TITLE
Deduplicate code in normal vs. fullscreen detail views

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#198]
E.g. `ui/src/scenes/Home/components/DetailViewContainer/DetailViewContainer.js` and `ui/src/scenes/RealityDetails/components/FullscreenDetailViewContainer/FullscreenDetailViewContainer.js` are veeery similar. Same thing for related files like `DetailView.js` and `FullscreenDetailView.js`.

**Comment by aerugo** [comment]
Hah, yes. Sorry, I wrote that feature in a hurry and was sloppy. Scuzi for
the mess!
