### ISSUE TITLE
Don't require nodeId in url for both need and resp when viewing a resp

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#203]
I.e. we just need the resp's nodeId in the url when viewing a resp

Just makes the links longer and makes the links break if you move a resp to another need

**Comment by Powersource** [comment]
I think this might be even more relevant/almost a blocker now that we don't want users to be able to select needs directly

**Comment by aerugo** [comment]
Hmm, yeah. Fair enough. If we do this, we should probably allow for both
formats to protect legacy links lying around though. Would that be hard?

**Comment by Powersource** [comment]
mmm yeah might be easy if we have back compat just for resps. 2 cases:
1. A user follows an old link to a need. New format thinks it's a resp but can't find it so it's rendered just like visiting /
2. A user follows an old link to a resp. We make a new route that matches those long urls and redirect to the respId we found in the url.

would that be fine?

**Comment by aerugo** [comment]
Yup, all good!
