### ISSUE TITLE
Migrate Kiez Burn to Plato's servers

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#207]
Never knew they were using Realities, so cool!! https://realities.kiezburn.org

They want to move their realities org to our servers. Here's an approximate todolist on how to make that happen

* [ ] They want to use their own domain, so we need to make that possible
  * [ ] Refactor logic out of dreams (into plato core?) that handles automatically adding redirect urls to keycloak
  * [ ] Maybe we need to switch to auth0-react instead of oidc-react at this point? Did you have to switch to nextjs-auth0 to get the subdomains to work @gustavlrsn ? https://github.com/Edgeryders-Participio/realities/issues/195
  * [ ] Switch to putting the orgSlug in a subdomain instead of the normal slug. Like dreams has it, orgname.realities.platoproject.org instead of realities.platoproject.org/orgname
  * [ ] Let an org set a custom domain if wanted
* [ ] They want to migrate needs/resps/etc (not users though)
  * [ ] Make export and import scripts. I'm thinking we could either
    * Export to some custom json format that we then can import from. We might be able to use this kind of thing also when we'll add fixtures for e2e tests
    * Open two connections, one to each server, and beam it over. Probably a bit simpler to code but easier to fuck up. Not too much of a problem though as long as we have backups.
  * [ ] Get access to their servers
  * [ ] Backup their server and our own
  * [ ] Migrate

**Comment by hesslau** [comment]
hello there! I'm the guy who setup the whole Kiez Burn online infrastructure and asked Hugi to make some space for us at Plato.
Thanks for taking this on! Let me know if you need anything (like access to our servers).

> They want to migrate needs/resps/etc (not users though)
Well, we would love to migrate users if possible. But afaik that would be quite tricky

**Comment by Powersource** [comment]
Hi! About the users, I think in neo4j we're still identifying users based on their email and not their keycloak IDs (we should move to doing that at some point in the future though) so migrating the neo4j nodes from one db to the other might not be too hard. People would just have to make a new account in our keycloak and it should connect correctly, but that's pretty easy.

**Comment by hesslau** [comment]
sounds good!

do you have a time estimate for this? just to know if this will take days or weeks and let the team know

**Comment by Powersource** [comment]
I'm gonna finish up https://github.com/Edgeryders-Participio/realities/pull/206 but after that I'll switch to working on this. Hard to guess but roughly a month.

**Comment by aerugo** [comment]
> Hard to guess but roughly a month.

When making this estimate, could be split it to two estimates? One for the custom domain, and one for the migration?

I have a feeling that perhaps a quick and dirty manual migration using good old copy and paste might perhaps be faster and does not require developer hours.

**Comment by Powersource** [comment]
> a quick and dirty manual migration using good old copy and paste

Yeah we could in theory do that if the person who'd do it is fine with it. And if the domain isn't a critical feature you could be up and running within a few days (followed by me working on the domain stuff as first priority).

**Comment by aerugo** [comment]
Hmm, it looks like Kiez might be in some trouble: https://realities.kiezburn.org/
@hesslau did you backup your dataset before hobby plans were shut down on graphenedb?

https://www.graphenedb.com/blog/2020/09/10/new-plans/

**Comment by aerugo** [comment]
I recently got this email from GrapheneDB about another of my projects:

> We're reaching out to let you know that we're shutting down as planned all Hobby databases on January 26th. Your Sandbox and Developer databases will disappear from our admin console and you will lose access to your dataset. Please export from our admin console before the 26th to avoid losing your data.

**Comment by hesslau** [comment]
@aerugo well yes, I saw those mails from graphenedb yesterday. but luckily we are able to get a backup of our database.

now that we don't have a working realities instance it would be great if we could migrate to plato soon (quick 'n dirty?), as the event team & board are actively using it. well, would be if they could.

dreams isn't crucial right now. also I'd say we use the default plato domain for now and switch to a kiezburn.org subdomain later if possible

**Comment by aerugo** [comment]
So the fastest way of doing this would probably be:

- We create a normal Realities org on Plato
- We set up a local Neo4j instance
- We export all responsibilities and needs to a CSV
- We crowdsource to the Kiez community to quickly manually migrate the data
to the new Realities

We can ofc also write a migration script like we had planned, however that
will take longer (maybe 2 weeks instead of 2 days) since we need to be
really careful.
What do you think?

**Comment by hesslau** [comment]
sounds like a good idea. let me talk to vero, our realities mastress, to hear what she thinks about this. In the meantime I'll forward you the backup once I have it.

**Comment by Powersource** [comment]
Since it sounds like the migration will be taken care of manually I've split out the domain issue here https://github.com/Edgeryders-Participio/realities/issues/210 and will be closing this issue. Will also downprioritize it a bit and first work on fixing UX issues ( https://github.com/Edgeryders-Participio/realities/issues/96 ) since I think that will benefit you more sooner
