### ISSUE TITLE
Status indicator design and implementation

### ISSUE THREAD

**Issue by aerugo** [Edgeryders-Participio/realities#21]
We should have a status indicator to determine if a need/responsibility needs some extra attention. This does not necessarily equate to that it's "done/in-progress/to-do" since needs/responsibilities are not tasks. We want something like a traffic light green/yellow/red.

**Comment by erikfrisk** [comment]
@aerugo Is this issue fixed as of the Tunisia hackathon? Can we close this issue or do we need to add to the indicator before we do so?

**Comment by Powersource** [comment]
Yeah we have those red dots, they might be enough for now?
