### ISSUE TITLE
When a person creates an org, also mark them as an admin for the org

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#213]
Right now we're not at all keeping track of who should in the future e.g. be allowed to change bigger settings for an org

Would probably be good to have this logic in plato-core

**Comment by Powersource** [comment]
Made an issue in plato core https://github.com/Edgeryders-Participio/plato-core/issues/6

**Comment by aerugo** [comment]
We are now handling this on Dreams, so closing for now.
