### ISSUE TITLE
Add simple authentication on an instance level

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#214]
An instance admin should be able to configure so that only someone with an account can view and edit the instance

A much simpler version of https://github.com/Edgeryders-Participio/realities/issues/182 (we should still do that one, but this one has a bigger effect since it makes it easier for external orgs to try it out and feel safe)

**Comment by aerugo** [comment]
If we implement #182 then this is redundant, right? In that case I say we close this one and just implement #182.

**Comment by Powersource** [comment]
Yeah pretty much
