### ISSUE TITLE
Switch Need descriptions from being a block of markdown to being plaintext and just a few lines

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#220]
As part of simplifying and de-emphasizing needs, and will save space in the new ui

what do you think @aerugo ?

**Comment by aerugo** [comment]
Yes, agree.

**Comment by aerugo** [comment]
Closing as we should probably rather do #150

**Comment by Powersource** [comment]
I'd argue we'll do #150 by mostly doing what's described in this issue, but I'll mention that in a comment in that one
