### ISSUE TITLE
Getting automatically logged out on localhost after 10-ish seconds in Firefox with Strict tracking protection

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#229]

**Comment by Powersource** [comment]
Works in production at least

Idk if we were getting this before but there's an error in the console pointing here https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign  
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/State_Partitioning#dynamic_state_partitioning  
https://blog.mozilla.org/security/2021/01/26/supercookie-protections/

So my current theory is that these heuristics hit us for some reason on localhost. I recently updated firefox on my machine.

Could also be related to fb1a3f8bbef41dfd4470d687647b681576834888 . At first that was broken (tests didn't even pass) because I hadn't updated the allowed redirect urls in keycloak, but that's done now so you can at least log in, if briefly, now. The issue could be related to some old cache or something around this.

**Comment by Powersource** [comment]
Screenshot of log

![image](https://user-images.githubusercontent.com/1427063/111172765-62961380-85a6-11eb-9f2d-4eba54442f79.png)

Tested and reproduces in private browsing as well

**Comment by Powersource** [comment]
Doesn't reproduce in chrome

**Comment by Powersource** [comment]
Only happens on Strict tracking protection in firefox, not Standard.

Tried upgrading react and oidc-react but didn't seem to help https://github.com/Edgeryders-Participio/realities/pull/230

**Comment by Powersource** [comment]
Opened an issue in oidc-client-js https://github.com/IdentityModel/oidc-client-js/issues/1321

**Comment by Powersource** [comment]
Fixing for now by me disabling Strict tracking protection :P

**Comment by aerugo** [comment]
So can we close this?

**Comment by Powersource** [comment]
mm sure but we should be ready for more strict 3rd party cookie blocking coming and biting us in the future
