### ISSUE TITLE
Remove all deprecated Lifecycle methods

### ISSUE THREAD

**Issue by belaldabous** [Edgeryders-Participio/realities#54]
There is one call to componentWillReceiveProps and one to componentWillMount.

Since these lifecycle methods will be deprecated by React, it's best to replace them with others, eg  componentDidUpdate,  which could be used for both.

See [this blog post](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) for more info.

**Comment by aerugo** [comment]
@Powersource, is this still relevant, or should we close it?

**Comment by Powersource** [comment]
We've fixed most/all of this, I don't remember seeing the warning in a while.
