### ISSUE TITLE
Add  a quick tutorial for auth0 configuration

### ISSUE THREAD

**Issue by csirvente** [Edgeryders-Participio/realities#76]
As I forked the project I run into a Auth0 login issue, apparently I am not alone. It would be nice to add a quick tuto on how to configure the Auth0 account, in the readme or a linked doc, as it is a tricky step. The overall docs are pretty clear by the way.

**Comment by Powersource** [comment]
I think we're aiming to switch away from auth0, correct me if I'm wrong @aerugo , so I'll close this if you don't mind :)

**Comment by aerugo** [comment]
Yes, we’re moving away from Auth0, so go ahead and close it.
