### ISSUE TITLE
Add section "Links/ressources" in the description of a Responsibility

### ISSUE THREAD

**Issue by andreasfmwolf** [Edgeryders-Participio/realities#77]
Adding a section "Links/ressources" in the description of a Responsibility will nudge that Realizers of the past years will link relevant documents to the Responsibility.

**Comment by Powersource** [comment]
We now have a default responsibility description template. So you could add a section like this if you want :) 

Not very easy to edit it so far though (you'd have to poke in the database) but that's for another issue.
