### ISSUE TITLE
Redesign start page

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#96]
The whole column system is pretty confusing

**Comment by Powersource** [comment]
As a simple solution maybe just add scrollbars to the needs/resps columns so you don't have to scroll away from everything else when you're browsing in them

**Comment by Powersource** [comment]
Maybe a good step is to find other apps where they've solved the same/similar ux problem so we can copy what they're doing.

**Comment by aerugo** [comment]
I think we might want to consider a collapsing one column menu, with Needs
as selectable “folders” of Responsibilities.

Perhaps it could be a good idea to do quick design session on this soon?
It’s really about time to redesign the UX a bit based on having used now
for a few years. Maybe we could do that this week already?

**Comment by Powersource** [comment]
I like the idea of having a tree-ish (1 level deep) list. I wonder how it should work when the list of resps is long, maybe just a max height on it and then a scrollbar. And I wonder if this would be much of an improvement on mobile. That's probably the harder challenge.

And yeah a design session this week could be nice.

**Comment by Powersource** [comment]
Hugi and I had the design session (it was discussed later in the team that we probably should have a bigger design session with the whole team later) and that resulted in this https://forum.blivande.com/t/new-layout-for-realities-work-in-progress/1869

I'm thinking to close this issue we'd merge a PR that 
* [ ] Combines needs/resps into the tree structure
* [ ] You can't directly visit needs, they only appear directly above their resps
* [ ] Before doing this PR we'd want to have already removed Realizers (related issue https://github.com/Edgeryders-Participio/realities/issues/127 ) and other fields from needs, probably in a separate PR
